### ISSUE TITLE
Store cookies after application exit?

### ISSUE THREAD

**Issue by rizkyputrapb** [jossef/requests#72]
Hi, I just want to ask if the current version stores the cookies even after the application exits? or should I use shared preferences to store the cookies and then set the cookies when opening the app again? thanks!

**Comment by sehnryr** [comment]
From version 4.3.0 onward, requests will not store cookies in the local storage by itself. Then, to store the cookies, you could use whatever storage system that suits you the best, like shared preferences in your case.

**Comment by sehnryr** [comment]
Since cookies should not store sensitive data, it's safe to use shared preferences.

There was quite the debate in issue #1 to chose a secured system to store the cookies, but in the end, since cookies should not handle sensitive data, there is no need to have a better and more secure way to score cookies compared to modern browsers, and I also concluded that it would be too restrictive to impose to the end user a storage system only for cookies.

**Comment by philippkeller** [comment]
So the current implementation does not store cookies when the app ist closed, right? So I would need to store the cookie myself. Based on the debate on #1 you consider it still safe to use [shared_preferences](https://pub.dev/packages/shared_preferences) for this, right?

**Comment by sehnryr** [comment]
@philippkeller Since 4.3.0 requests will not store cookies by itself. This allows the user to have more control on how he wants to handle the cookies. And I don't think there is any problem with using shared_preferences or any other storage system if the cookies you are trying to save follow the simple rule of not storing sensitive data.
